SELECT DISTINCT
	DATA,
	U2.MATRICULA,
    U2.NOME AS FUNCIONARIO,
    TO_CHAR(MIN(DTINICIOOS), 'hh24:mi:ss') AS INICIO,
    TO_CHAR(MAX(DTFIMSEPARACAO), 'hh24:mi:ss') AS FIM,
    LPAD(TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24), 2, '0') || ':' || 
    LPAD(TRUNC(MOD((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60, 60)), 2, '0') || ':' || 
    LPAD(TRUNC(MOD((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60, 60)), 2, '0') AS TEMPO,
        TO_CHAR(TRUNC(MOD((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15), 60) / 3600), 'FM00') || ':' ||
    TO_CHAR(TRUNC(MOD((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15), 3600) / 60), 'FM00') || ':' ||
    TO_CHAR(MOD((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15), 60), 'FM00') AS PROJECAO,
    CASE 
        WHEN SUM(M.QT) = 0 THEN 0
        WHEN TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60) = 0 THEN 0
        ELSE ROUND((((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60))/((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15)),4)
    END AS PERCENTUAL,
    
    SUM(M.QT) AS ITENS,
    (CASE
    	WHEN (CASE WHEN SUM(M.QT) = 0 THEN 0 WHEN TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60) = 0 THEN 0 ELSE ROUND((((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60))/((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15)),4) END) < 0.8 THEN (SUM(M.QT))*1.2
    	WHEN (CASE WHEN SUM(M.QT) = 0 THEN 0 WHEN TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60) = 0 THEN 0 ELSE ROUND((((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60))/((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15)),4) END) BETWEEN 0.8 AND 1.2 THEN (SUM(M.QT))*1
    	WHEN (CASE WHEN SUM(M.QT) = 0 THEN 0 WHEN TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60) = 0 THEN 0 ELSE ROUND((((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60))/((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15)),4) END) > 1.2 THEN (SUM(M.QT))*0.8
    ELSE SUM(M.QT)*0 END)-(SUM(M.QT)) AS BONUS,
    (CASE
    	WHEN (CASE WHEN SUM(M.QT) = 0 THEN 0 WHEN TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60) = 0 THEN 0 ELSE ROUND((((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60))/((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15)),4) END) < 0.8 THEN (SUM(M.QT))*1.2
    	WHEN (CASE WHEN SUM(M.QT) = 0 THEN 0 WHEN TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60) = 0 THEN 0 ELSE ROUND((((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60))/((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15)),4) END) BETWEEN 0.8 AND 1.2 THEN (SUM(M.QT))*1
    	WHEN (CASE WHEN SUM(M.QT) = 0 THEN 0 WHEN TRUNC((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60) = 0 THEN 0 ELSE ROUND((((MAX(DTFIMSEPARACAO) - MIN(DTINICIOOS)) * 24 * 60 * 60))/((SUM(M.QT)*1)+(COUNT(DISTINCT E.RUA)*30)+(COUNT(DISTINCT E.CODENDERECO)*15)),4) END) > 1.2 THEN (SUM(M.QT))*0.8
    ELSE SUM(M.QT)*0 END) AS PONTOS,
    'ET' AS TIPO,
	NUMAGRUPADOR AS IDENTIFICADOR,
	CASE
		WHEN E.DEPOSITO = 2 THEN 'CONTROLADO'
		ELSE 'FARMA'
	END AS DEPOSITO
FROM 
    PCMOVENDPEND M
INNER JOIN PCENDERECO E ON E.CODENDERECO = M.CODENDERECO
INNER JOIN PCEMPR U2 ON U2.MATRICULA = CODFUNCOS
WHERE 1 = 1
    --AND M.DATA BETWEEN '26-MAR-2024' AND '31-MAR-2024'
    AND M.TIPOOS = 13
    AND M.CODOPER = 'S'
    AND M.DTESTORNO IS NULL
GROUP BY NUMAGRUPADOR,U2.NOME,DATA,U2.MATRICULA,E.DEPOSITO

UNION ALL

SELECT DISTINCT
    M.DATA,
    U1.MATRICULA AS MATRICULA,
    U1.NOME AS FUNCIONARIO,
    TO_CHAR(MIN(M.DTINICIOCONFERENCIA), 'hh24:mi:ss') AS INICIO,
    TO_CHAR(MAX(M.DTFIMCONFERENCIA), 'hh24:mi:ss') AS FIM,
    LPAD(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24), 2, '0') || ':' || 
    LPAD(TRUNC(MOD((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60, 60)), 2, '0') || ':' || 
    LPAD(TRUNC(MOD((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60, 60)), 2, '0') AS TEMPO,
    TRUNC(SUM(M.QT) * 3 / 60) || ':' || LPAD(MOD(SUM(M.QT) * 3, 60), 2, '0') AS PROJECAO,
    CASE 
        WHEN SUM(M.QT) = 0 THEN 0
        WHEN TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60) = 0 THEN 0.8
        ELSE ROUND(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60)/(SUM(M.QT) * 3),4)
    END AS PERCENTUAL,
    SUM(M.QT) AS ITENS,
    ((CASE 
        WHEN 
            ROUND(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60)/(SUM(M.QT) * 3),4) < 0.8 THEN SUM(M.QT) * 1.2
        WHEN 
            ROUND(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60)/(SUM(M.QT) * 3),4) BETWEEN 0.8 AND 1.2 THEN SUM(M.QT) * 1
        WHEN 
            ROUND(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60)/(SUM(M.QT) * 3),4) > 1.2 THEN SUM(M.QT) * 0.8
        ELSE 
            SUM(M.QT) * 0
    END )-SUM(M.QT)) AS BONUS,
    CASE 
        WHEN 
            ROUND(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60)/(SUM(M.QT) * 3),4) < 0.8 THEN SUM(M.QT) * 1.2
        WHEN 
            ROUND(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60)/(SUM(M.QT) * 3),4) BETWEEN 0.8 AND 1.2 THEN SUM(M.QT) * 1
        WHEN 
            ROUND(TRUNC((MAX(M.DTFIMCONFERENCIA) - MIN(M.DTINICIOCONFERENCIA)) * 24 * 60 * 60)/(SUM(M.QT) * 3),4) > 1.2 THEN SUM(M.QT) * 0.8
        ELSE 
            SUM(M.QT) * 0
    END AS PONTOS,
    'O.S' AS TIPO,
    M.NUMOS AS IDENTIFICADOR,
	CASE
		WHEN E.DEPOSITO = 2 THEN 'CONTROLADO'
		ELSE 'FARMA'
	END AS DEPOSITO
FROM 
    PCMOVENDPEND M
INNER JOIN PCEMPR U1 ON U1.MATRICULA = M.CODFUNCCONF
INNER JOIN PCENDERECO E ON E.CODENDERECO = M.CODENDERECO
WHERE 1 = 1
    --AND M.DATA BETWEEN '26-MAR-2024' AND '31-MAR-2024'
    AND M.CODOPER = 'S'
    AND M.DTESTORNO IS NULL
    AND M.TIPOOS = 13
GROUP BY 
    M.NUMOS, M.DATA, U1.NOME, NUMPED,U1.MATRICULA,E.DEPOSITO

UNION ALL

SELECT DISTINCT
E.DATA,
E.MATERRO AS MATRICULA,
F.NOME AS FUNCIONARIO,
CAST(E.DATA AS VARCHAR2(50)) AS INICIO,
CAST(E.DATA AS VARCHAR2(50)) AS FIM,
TO_CHAR(E.DATA, 'HH24:MI') AS TEMPO,
TO_CHAR(TO_DATE('18/11/2001 00:00:00', 'DD/MM/YYYY HH24:MI:SS'), 'HH24:MI') AS PROJECAO,
0 AS PERCENTUAL,
E.QT AS ITENS,
T.PESOERRO AS BONUS,
(E.QT*T.PESOERRO)*-1 AS PONTOS,
CAST('ERRO' AS VARCHAR2(50)) AS TIPO,
E.NUMOS AS IDENTIFICADOR,
	CASE
		WHEN EE.DEPOSITO = 2 THEN 'CONTROLADO'
		ELSE 'FARMA'
	END AS DEPOSITO
FROM
PCWMSERRO E
INNER JOIN PCWMSTIPOERRO T ON T.CODIGO = E.TIPOERRO
INNER JOIN PCMOVENDPEND M ON M.NUMOS = E.NUMOS
INNER JOIN PCENDERECO EE ON EE.CODENDERECO = M.CODENDERECO
INNER JOIN PCEMPR F ON F.MATRICULA = E.MATERRO
